name: my-check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v4
    - run: make package-install
    - run: pip install poetry
    - run: make build
    - run: make publish
    - run: make install
    - run: pip install pytest
    - name: Linter & Pytest
      run: |
          make check
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID:
      with:
        coverageCommand: make test-coverage
        debug: true
