name: my-check
on: push
jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install  --with flake8,pytest
      - name: Linter Test
        run:  |
          make lint
#          pip install flake8
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
